name: Build and Test

on:
  push:
    branches:
      - master
      - 2.4.x
  pull_request:
    branches:
      - master
      - 2.4.x
  workflow_dispatch:

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: show Ubuntu version
      run: cat /etc/os-release | grep PRETTY_NAME | awk -F '=' '{print $2}'
    - name: update build environment
      run: sudo apt-get update --fix-missing -y && sudo apt-get upgrade --fix-missing -y
    - name: install prerequisites
      run: sudo apt-get install -y avahi-daemon libavahi-client-dev libssl-dev libpam-dev libusb-1.0-0-dev zlib1g-dev
    - name: configure
      env:
        CC: /usr/bin/gcc
      run: ./configure --enable-debug --enable-maintainer
    - name: make
      run: make
    - name: test
      run: make test || cat test/error_log*

  build-linux-i386:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: show Ubuntu version
      run: cat /etc/os-release | grep PRETTY_NAME | awk -F '=' '{print $2}'
    - name: setup multiarch for i386
      run: sudo dpkg --add-architecture i386
    - name: update build environment
      run: sudo apt-get update --fix-missing -y
    - name: install prerequisites
      run: sudo apt-get install -y avahi-daemon libavahi-client-dev libavahi-client-dev:i386 libgnutls28-dev libgnutls28-dev:i386 libpam-dev libpam-dev:i386 libusb-1.0-0-dev libusb-1.0-0-dev:i386 zlib1g-dev zlib1g-dev:i386 crossbuild-essential-i386 libgcc-s1:i386 libstdc++6:i386
    - name: configure
      env:
        CC: /usr/bin/i686-linux-gnu-gcc
        CXX: /usr/bin/i686-linux-gnu-g++
      run: ./configure --enable-debug --enable-maintainer --host=i686-pc-linux-gnu --target=i686-pc-linux-gnu --with-tls=gnutls
    - name: make
      run: make
    - name: test
      run: make test || cat test/error_log*

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure --enable-debug --enable-maintainer --enable-sanitizer
    - name: make
      run: make
    - name: test
      run: make test || cat test/error_log*

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2.0.0
    - name: nuget restore
      run: cd vcnet; nuget restore cups.sln
    - name: msbuild
      run: cd vcnet; msbuild cups.sln
